pod 'Firebase/Core'
pod 'FirebaseUI'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Google'
pod 'FirebaseUI/Facebook'
pod 'FirebaseUI/OAuth' # Used for Sign in with Apple, Twitter, etc
pod 'FirebaseUI/Phone'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'Firebase/Analytics'
pod 'FBSDKLoginKit'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
target 'Gallery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gallery
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
end
